export type FurnitureItem = {
  id: string;
  name: string;
  furnitureType: string;
  price: number;
  style?: string;
  color?: string;
  material?: string;
  rating?: number;
  inStock?: boolean;
};

export const MOCK_FURNITURE: FurnitureItem[] = [
  // --- CHAIRS ---
  {
    id: 'P001',
    name: 'Velvet Accent Chair',
    furnitureType: 'Chair',
    price: 58900,
    style: 'Modern',
    color: 'Pink',
    material: 'Velvet',
    rating: 4.6,
    inStock: true,
  },
  {
    id: 'P002',
    name: 'Ergonomic Office Chair',
    furnitureType: 'Chair',
    price: 85000,
    style: 'Modern',
    color: 'Black',
    material: 'Mesh',
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'P003',
    name: 'Boho Rattan Chair',
    furnitureType: 'Chair',
    price: 60000,
    style: 'Bohemian',
    color: 'Natural',
    material: 'Rattan',
    rating: 4.4,
    inStock: true,
  },
  {
    id: 'P004',
    name: 'Dining Chair Set (x2)',
    furnitureType: 'Chair',
    price: 70000,
    style: 'Rustic',
    color: 'Walnut',
    material: 'Wood',
    rating: 4.3,
    inStock: true,
  },
  {
    id: 'P005',
    name: 'Lounge Recliner',
    furnitureType: 'Chair',
    price: 110000,
    style: 'Traditional',
    color: 'Brown',
    material: 'Leather',
    rating: 4.8,
    inStock: true,
  },

  // --- BEDS ---
  {
    id: 'P006',
    name: 'Wooden Bed Frame',
    furnitureType: 'Bed',
    price: 120000,
    style: 'Modern',
    color: 'Oak',
    material: 'Wood',
    rating: 4.3,
    inStock: true,
  },
  {
    id: 'P007',
    name: 'Platform Bed with Storage',
    furnitureType: 'Bed',
    price: 160000,
    style: 'Modern',
    color: 'Charcoal',
    material: 'Upholstered',
    rating: 4.5,
    inStock: true,
  },
  {
    id: 'P008',
    name: 'King Size Canopy Bed',
    furnitureType: 'Bed',
    price: 250000,
    style: 'Classic',
    color: 'Mahogany',
    material: 'Wood/Fabric',
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'P009',
    name: 'Minimalist Metal Bed',
    furnitureType: 'Bed',
    price: 85000,
    style: 'Minimalist',
    color: 'Black',
    material: 'Metal',
    rating: 4.1,
    inStock: true,
  },
  {
    id: 'P010',
    name: 'Tufted Headboard Bed',
    furnitureType: 'Bed',
    price: 145000,
    style: 'Contemporary',
    color: 'Grey',
    material: 'Velvet',
    rating: 4.7,
    inStock: true,
  },

  // --- WARDROBES ---
  {
    id: 'P011',
    name: 'Wardrobe (2-door)',
    furnitureType: 'Wardrobe',
    price: 90000,
    style: 'Modern',
    color: 'Oak',
    material: 'Wood',
    rating: 4.0,
    inStock: true,
  },
  {
    id: 'P012',
    name: 'Sliding Mirror Wardrobe',
    furnitureType: 'Wardrobe',
    price: 180000,
    style: 'Contemporary',
    color: 'White',
    material: 'MDF/Glass',
    rating: 4.5,
    inStock: true,
  },
  {
    id: 'P013',
    name: 'Vintage Wooden Armoire',
    furnitureType: 'Wardrobe',
    price: 150000,
    style: 'Vintage',
    color: 'Cherry',
    material: 'Solid Wood',
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'P014',
    name: 'Corner Wardrobe Unit',
    furnitureType: 'Wardrobe',
    price: 120000,
    style: 'Modern',
    color: 'Black',
    material: 'Manufactured Wood',
    rating: 4.2,
    inStock: true,
  },
  {
    id: 'P015',
    name: 'Open Closet System',
    furnitureType: 'Wardrobe',
    price: 75000,
    style: 'Industrial',
    color: 'Natural',
    material: 'Metal/Wood',
    rating: 4.6,
    inStock: true,
  },

  // --- SOFAS ---
  {
    id: 'P016',
    name: 'Mid-Century Sofa',
    furnitureType: 'Sofa',
    price: 250000,
    style: 'Mid-Century Modern',
    color: 'Teal',
    material: 'Fabric',
    rating: 4.8,
    inStock: true,
  },
  {
    id: 'P017',
    name: 'Leather Loveseat',
    furnitureType: 'Sofa',
    price: 320000,
    style: 'Traditional',
    color: 'Brown',
    material: 'Leather',
    rating: 4.9,
    inStock: true,
  },
  {
    id: 'P018',
    name: 'L-Shaped Sectional',
    furnitureType: 'Sofa',
    price: 450000,
    style: 'Modern',
    color: 'Light Grey',
    material: 'Linen',
    rating: 4.7,
    inStock: true,
  },
  {
    id: 'P019',
    name: 'Sleeper Futon',
    furnitureType: 'Sofa',
    price: 120000,
    style: 'Minimalist',
    color: 'Navy Blue',
    material: 'Microfiber',
    rating: 4.2,
    inStock: true,
  },
  {
    id: 'P020',
    name: 'Curved Bouclé Sofa',
    furnitureType: 'Sofa',
    price: 380000,
    style: 'Contemporary',
    color: 'Cream',
    material: 'Bouclé',
    rating: 4.9,
    inStock: true,
  },
];
