// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5NTwxnWrbVkGnJQvIwIlg7z2bWmNj0Nk',
    appId: '1:93470454666:web:ae5037a87e9524a77b0e73',
    messagingSenderId: '93470454666',
    projectId: 'pocketroom-80f62',
    authDomain: 'pocketroom-80f62.firebaseapp.com',
    storageBucket: 'pocketroom-80f62.firebasestorage.app',
    measurementId: 'G-BLD3HXTGTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqpQLCadDl71NTcRRTohJccNLKiYipGSQ',
    appId: '1:93470454666:android:0f59911e1613bf507b0e73',
    messagingSenderId: '93470454666',
    projectId: 'pocketroom-80f62',
    storageBucket: 'pocketroom-80f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRoh8a-di_T2i1PTB_mE9AkxwbB2sdR1g',
    appId: '1:93470454666:ios:98b0b1196fd0a6f87b0e73',
    messagingSenderId: '93470454666',
    projectId: 'pocketroom-80f62',
    storageBucket: 'pocketroom-80f62.firebasestorage.app',
    iosBundleId: 'com.example.pocketroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5NTwxnWrbVkGnJQvIwIlg7z2bWmNj0Nk',
    appId: '1:93470454666:web:9d94fb8ceec779787b0e73',
    messagingSenderId: '93470454666',
    projectId: 'pocketroom-80f62',
    authDomain: 'pocketroom-80f62.firebaseapp.com',
    storageBucket: 'pocketroom-80f62.firebasestorage.app',
    measurementId: 'G-2R43LMMGKW',
  );

}