jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Flutter
        run: ... // installation commands
      - name: Analyze code (don't fail job)
        run: flutter analyze || true
      // Other steps...